install.packages('devtools', dependencies = T)

library(devtools)

install_version("rmarkdown", version = "1.12")
install_version("magrittr", version = "1.5")
install_version("boot", version = "1.3-20")
install_version("HDInterval", version = "0.2.0")
install_version("BayesFactor", version = "0.9.12-4.2")
install_version("here", version = "0.1")
install_version("compute.es", version = "0.2-2")
install_version("tidyverse", version = "1.2.1")
install_version("conflicted", version = "1.0.1")
install_version("knitr", version = "1.12")
install_version("kableExtra", version = "1.1.0")
install_version("car", version = "3.0-2")
install_version("psych", version = "1.8.12")

install_version("MASS", version = "7.3-51.4")
install_version("candisc", version = "0.8-0")
install_version("viridis", version = "0.5.1")
install_version("ggrepel", version = "0.8.0")
install_version("broom", version = "0.5.2")
install_version("janitor", version = "1.2.0")
