---
fontsize: 11pt
geometry: margin=1in
header-includes: |
  \usepackage[natbibapa, sectionbib, tocbib]{apacite}
  \usepackage[utf8]{inputenc}
  \usepackage[singlelinecheck = off]{caption}
  \usepackage{lmodern}
  \usepackage{microtype}
  \usepackage{multirow}
  \usepackage[inline]{enumitem}
  \usepackage{array}
  \usepackage[htt]{hyphenat}
  \usepackage{booktabs}
  \usepackage[euler]{textgreek}
  \usepackage{float}
  \usepackage[doublespacing]{setspace}
  \usepackage{fancyhdr}
  \captionsetup[table]{width=\textwidth}
  \setlength{\parindent}{2em}
  \fancyhf{}
  \fancyhead[RH]{\thepage}
  \renewcommand{\headrulewidth}{0pt}
  \pagestyle{fancy}
  \hypersetup{colorlinks = true, linkcolor = blue, urlcolor = black, citecolor = blue}
  \DeclareCaptionFormat{apa}{#1#2\\[1em]#3}
  \captionsetup*[table]{labelsep = none, textfont = it, format = apa, width = .8\textwidth}
  \captionsetup*[figure]{labelsep = period, labelfont = it, position = below, skip = -10pt}
output:
  pdf_document:
    keep_tex: yes
    toc: no
---

```{r set, echo = F, include = F}
library(knitr)
```

```{r method, child = 'methods.Rmd'}
```

```{r results, child = 'analyses-main.Rmd'}
```

\bibliographystyle{apacite}
\bibliography{../../paper/reference.bib}