---
fontsize: 11pt
geometry: margin=1.8cm
output:
  pdf_document:
    keep_tex: true
    toc: false
header-includes: |
    \usepackage[natbibapa, sectionbib, tocbib]{apacite}
    \usepackage[utf8]{inputenc}
    \usepackage{caption}
    \usepackage{lmodern}
    \usepackage{multirow}
    \usepackage[inline]{enumitem}
    \usepackage{array}
    \usepackage[htt]{hyphenat}
    \usepackage{booktabs}
    \usepackage[euler]{textgreek}
    \usepackage{float}
    \usepackage[onehalfspacing]{setspace}
    \captionsetup[table]{width=\textwidth}
    \hypersetup{colorlinks = true, linkcolor = blue, urlcolor = red}
---

```{r setup-methods, include = FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, dev = 'pdf')

options(digits = 5)

library(kableExtra)
library(here)
# NOTE: this will load {magrittr}, {here}, {conflicted} and {tidyverse}. also,
# `conflict_prefer`s filter from {dplyr}
# furthermore, it loads 3 data.frames: (1) `dat` which contains the pooled data run
# through `2-wrangling-main.R`, (2) `datHard` which is `dat` with all the hard
# exclusion criteria applied (as described in `analysis-plan.md`), and (3)
# `datSoft` which is `datHard` with the soft exclusion criteria applied (as
# described in `analysis-plan.md`)
source(here('wrangling', '3-exclusion-criteria.R'))

conflict_prefer('select', 'dplyr')
theme_set(theme_minimal())

# source helper functions
source(here('helpers', 'manova-helpers.R'))
```

## Participants and design

Undergraduate and graduate phontecis and psychology students (80.8% female,
median age = 21, IQR = 3, range = [18, 31], total \(N\) = `r nrow(dat)`)
from the University of Zagreb
participated in the study in exchange for course credit. Participants were
randomly assigned to one of five groups which differed in the type of activity
they engaged in between parts of the text they have read and in whether they
received feedback on their intermittent test achievement or not.

## Materials and procedure

### Materials

Participants read a text on the evolution, ecological and biological characteristics
of weeds. The text was taken from a chapter in a Croatian university-level textbook.
Some sentences and passages were slightly modified, so as to avoid odd language
constructions; Latin plant names were translated to Croatian, and some plants
were removed from the text to make it less difficult for the target participant
population. The text was divided into three parts of 874, 754, and 835 words,
respectively. Additionaly, there was a practice text taken from the same chapter,
but unrelated to any of the other three parts of the text (768 words).

Forty-four content related questions with four response options were generated
from the presented texts. Four questions were presented after the practice text,
ten after each of the first two parts (only to the participants in the content
related test condition), and twenty after the third part of the text (to all
participants).
Starting from the second ten-question-set, the distractor options were chosen so that
(a) two distractors were plausible, but unrelated to the text, and
(b) one distractor was a term or concept mentioned in the previous part of the
text --- this was considered to be the "intrusive" option.

An example question is:
\begin{quotation}
\noindent Compared to younger weeds, older weeds:
\begin{enumerate}[label = (\alph*)]
\item have a stronger allelopathic effect
\item contain more phytotoxins
\item \label{optCorr} \textbf{contain less inhibitory matter}
\item \label{optIntr} \textit{show greater plasticity.}
\end{enumerate}
\end{quotation}
Option \ref{optCorr} is the correct answer, and option \ref{optIntr} is the
intrusive distractor.

Further, twenty-four general knowledge questions were generated. These questions were
presented to participants in the general knowledge test condition, after the first
two parts of the text. An example general knowledge question is:
\begin{quotation}
\noindent The name of Kurt Vonnegut's famous anti-war novel is:
\begin{enumerate}[label = (\alph*)]
\item \textbf{Slaughterhouse Five}
\item All Quiet on the Western Front
\item A Farewell to Arms
\item Journey to the End of the Night.
\end{enumerate}
\end{quotation}

At the beginning of the session, participants' ID, age and sex information was
collected. At the end of the session, participants were asked to estimate how
much of each text they have read.
The texts and questions were presented on a personal computer, in an application
constructed using the open source `oTree` framework
\citep[version 2.1.35,][]{chenOTreeOpensourcePlatform2016}
for the Python programming language (version 3.6.4, October 20, 2018).

### Procedure

Participants were first given a brief introduction to the study, and were
encouraged to carefully read and follow the written instructions.
Then, they were led to one of six compartments containing a computer, which was
running a fullscreen instance of the `oTree` application with
a randomly chosen experimental condition. There, participants read the informed consent
form and, in case there were no questions, started the experiment.

After entering their personal information, participants were presented with
instructions for their first task, which was to read the practice text at a speed
that comes naturally to them. They were to click a button at the bottom of the text
when they have finished reading it. Unbeknownst to the participants, the
time they took to read the practice text was recorded, and used as the basis
for determining the reading time limits for the remaining texts. Results of a pilot
study using different participants have shown that most participants found 4 minutes
to be too short, and 9 minutes too long, so we have set the lowest possible limit
to 5 minutes, and the longest to 8 minutes.

Next, participants were familiarised with the interpolated activity they were
going to perform during the main part of the procedure. The rereading group
reread the practice text (this time with the time limit applied), the general
knowledge test group answered four general knowledge questions, and the content
related test group answered four questions based on the practice text.

Subjects in the rereading and general knowledge conditions
also answered the four questions related to the practice text, so as to
familiarise themselves with the scope and specificity level of questions that they
will receive after reading the final text. All participants were told that
there would be a cumulative test after the final text, examining their knowledge
of the three texts following the practice text. In reality, the final test examined
only the knowledge of the final text.

Participants assigned to the feedback condition also received feedback on their practice
test achievement. Feedback was presented on a separate screen, which listed the
questions, the participant's answers, and the correct answers in a tabular format.
Incorrectly answered questions were highlighted in red, and correctly answered
questions in green. After 40 seconds
elapsed, a "Next" button appeared, allowing participants to proceed to the next
text. By setting this cooldown period and by emphasising that there would be a cumulative test,
we wanted to encourage our participants to carefully examine the feedback.
The feedback was presented for maximally 60 seconds, after which the application
proceeded to the next text.

After the practice round, participants proceeded to the main texts, engaging
in the interpolated activities they were assigned. After the third text, all
participatns were presented with twenty questions examining their knowledge of
the third text. The computer recorded whether a participant correctly answered
a question and whether the participant chose an intrusive distractor. This allowed
us to compute our dependent variables --- the total number of correct answers
and the total number of intrusive distractors chosen.